menu:
  - name: Home
    path: /
    position: left
  - name: Tutorials
    path: /tutorials
    position: left
  - name: Examples
    path: /examples
    position: left
  - name: Documentation
    path: /documentation
    position: left
  - name: Play Online
    path: /play
    position: right
    icon: fas fa-laptop-code
  - name: GitHub
    link: https://github.com/jpkli/p4
    position: right
    icon: fab fa-github

docs:
  - name: Overview
    file: overview.md
    desc: Overview
    path: /documentation/overview

  - name: Data I/O
    file: data.md
    desc: Upload data to GPU and get the data processing results back.
    path: /documentation/data

  - name: Transformation
    file: transformation.md
    desc: Process data using common transformations such as filter and group-by.
    path: /documentation/transformation

  # - name: Match
  #   path: /documentation/match
  #   file: match.md
  #   parent: 'Transformation'

  # - name: Derive
  #   path: /documentation/derive
  #   file: derive.md
  #   parent: 'Transformation'

  # - name: Aggregate
  #   path: /documentation/aggregate
  #   file: aggregate.md
  #   parent: 'Transformation'

  - name: Visualization
    file: visualization.md
    desc: Setup views and plot the data processing results with various visualizations.
    path: /documentation/visualization

  - name: Interaction
    file: interaction.md
    desc: Enable user interactions for data transformations and visualizations.
    path: /documentation/interaction

  - name: Annotation
    file: annotation.md
    desc: Add annotations and marker on visualizations.
    path: /documentation/annotation

  - name: Extension
    file: extension.md
    desc: Extend or add custom data transformation and visualization operations.
    path: /documentation/extension

examples:
  - name: Example Plots
    examples:
    - name: Bar Chart
      image: https://jpkli.github.io/demos/images/p4/barchart.png
      url: /play/bar-chart

    - name: Column Chart
      image: https://jpkli.github.io/demos/images/p4/column-chart.png
      url: /play/column-chart

    - name: Scatterplot
      image: https://jpkli.github.io/demos/images/p4/scatterplot.png
      url: /play/scatter-plot
  
    - name: Line Chart
      image: https://jpkli.github.io/demos/images/p4/line-chart.png
      url: /play/line-chart

    - name: Color Lines
      image: https://jpkli.github.io/demos/images/p4/color-lines.png
      url: /play/color-lines

    - name: Area Chart
      image: https://jpkli.github.io/demos/images/p4/area-chart.png
      url: /play/area-chart

    - name: 2D Heatmap
      image: https://jpkli.github.io/demos/p4/images/heatmap.png
      url: /play/heatmap

    - name: Parallel Coordinates
      image: https://jpkli.github.io/demos/p4/images/parallel-coordinates.png
      url: /play/parallel-coordinates

    - name: Colored Bar Chart
      image: https://jpkli.github.io/demos/p4/images/colorbars.png
      url: /play/derive-match-group

    - name: Brushing and Linking
      image: https://jpkli.github.io/demos/p4/images/brush-link.png
      url: /play/brush-link

    # - name: Enhanced Perception
    #   image: https://jpkli.github.io/demos/p4/images/perception-line.png
    #   url: /play/perception-line

    - name: Facets
      image: https://jpkli.github.io/demos/p4/images/brush-link.png
      url: /play/facets

  # - name: Colors
  #   examples:
  #   - name: Colored Bar Chart
  #     image: https://jpkli.github.io/demos/p4/images/colorbars.png
  #     url: /play/derive-match-group
  #   - name: Enhanced Perception
  #     image: https://jpkli.github.io/demos/p4/images/perception-line.png
  #     url: /play/perception-line
  #   - name: Colored Bar Chart
  #     image: https://jpkli.github.io/demos/p4/images/colorbars.png
  #     url: /play/derive-match-group
  # - name: Multiple Views
  #   examples:
  #     - name: Brushing and Linking
  #       image: https://jpkli.github.io/demos/p4/images/brush-link.png
  #       url: /play/brush-link