tabs:
  - name: Home
    path: /
    file: home.md
  - name: Usage
    path: /usage
    file: overview.md
  - name: Tutorials
    path: /tutorial
    file: tutorial.md
  - name: Examples
    path: /examples
    file: docs.md
  - name: Documentation
    path: /documentation
    file: docs.md

docs:
  - name: Overview
    file: overview.md
  - name: Data I/O
    file: data.md
  - name: Transformation
    file: transformation.md
  - name: Visualization
    file: visualization.md
  - name: Interaction
    file: interaction.md
  - name: Annotation
    file: annotation.md
  - name: Extension
    file: extension.md

